### ISSUE TITLE
rviz无法启动

### ISSUE THREAD

**Issue by sitchain** [elephantrobotics/myCobot#19]
ros已启动，
通过命令roslaunch mycobot_ros mycobot_slider.launch
无法启动rviz
rosrun rviz rviz  无法启动

**Comment by zlj-zz** [comment]
我很抱歉你遇到这样的问题。这很明显是rviz的安装问题。你可以去看看下面链接的文档，我们有提供ros整个安装的教程。你可以参考它。

[https://github.com/elephantrobotics/mycobot_ros](https://github.com/elephantrobotics/mycobot_ros)

但是这不是ros包的问题，我们无法提供太多的帮助在这个上面。
