### ISSUE TITLE
590行与591行是否写反了？

### ISSUE THREAD

**Issue by LW-SCU** [elephantrobotics/myCobot#6]
![image](https://user-images.githubusercontent.com/28128257/104808441-49c8e600-5821-11eb-9f17-3fc338676486.png)

https://github.com/elephantrobotics/myCobot/blob/fea11f7402d5ecf8cbccb079db098264ebd9656b/Arduino/MycobotBasic/MycobotBasic.cpp#L591

**Comment by wxy6655** [comment]
好的，我们会测试后进行修改，感谢你的反馈。
